Factories return ObservableSettings where applicable
russhwolf/multiplatform-settings pull request #126
Opened 2022-09-12 06:04 UTC by svenjacobs

As discussed [here](https://github.com/russhwolf/multiplatform-settings/issues/125#issuecomment-1243118303), Factories that create `ObservableSettings` now return that type. Therefore casting to `ObservableSettings` is not required anymore.

2022-09-12 06:07 UTC, svenjacobs commented on multiplatform-settings/src/commonMain/kotlin/com/russhwolf/settings/Settings.kt
>      public interface Factory {
I thought about adding a generic type `out T : Settings`. Thus the interface expresses that derivations might be returned. However since probably implementations of `Factory` are mostly used to create instances and not the `Factory` interface, this is not a required change.

2022-09-19 03:17 UTC, russhwolf requested changes
Run the `apiDump` gradle task and commit the resulting `.api` file diff to fix the build failure. This is a breaking API change but that's the whole point of getting it in before the final 1.0

2022-09-19 03:17 UTC, russhwolf commented on multiplatform-settings-test/src/commonMain/kotlin/com/russhwolf/settings/MapSettings.kt
> +        public override fun create(name: String?): ObservableSettings {
I actually like this better if it returns the specific type (`MapSettings`, `AndroidSettings`, etc). Because the factory is associate with the class anyway, this should future-proof slightly better if other interfaces ever get added (though I don't expect that to happen currently)

2022-09-19 03:22 UTC, russhwolf commented on multiplatform-settings/src/commonMain/kotlin/com/russhwolf/settings/Settings.kt
>      public interface Factory {
My original use-case for factories was to use them from common, so you inject a factory once and then can instantiate multiple `Settings` instances from common. And for that use-case, the generic would help because if all platforms are using `ObservableSettings`, you could have an `ObservableSettings` factory in common. On the other hand, that feels like it might start overcomplicating things, especially for such a simple interface that's easy for consumers to recreate themselves if they want to change it, so I'm fine leaving the generic out.

2022-09-19 05:32 UTC, svenjacobs commented on multiplatform-settings-test/src/commonMain/kotlin/com/russhwolf/settings/MapSettings.kt
> +        public override fun create(name: String?): ObservableSettings {
Done

2022-09-20 01:19 UTC, russhwolf approved these changes

2022-09-20 01:21 UTC, merged